apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-api-gitops
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokes-api
      env: production
  template:
    metadata:
      labels:
        app: jokes-api
        env: production
    spec:
      containers:
      - command:
        - sh
        - -c
        - bundle exec rackup -p 3000 -o 0.0.0.0
        image: guillermijas/jokes-api-gitops:master-9
        name: app
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 30m
            memory: 10Mi
