---
apiVersion: v1
kind: Service
metadata:
  name: jokes-api-gitops
  namespace: default
  labels:
    app: jokes-api
    env: production
spec:
  type: ClusterIP
  selector:
    app: jokes-api
    env: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
