---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jokes-api-gitops
  namespace: default
spec:
  interval: 5m0s
  path: ./applications/jokes-api-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
  validation: client
